name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # or any branch you prefer

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: minikube deploy

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/my-springboot-app:latest

      # OPTIONAL: Trigger Deployment Script
      - name: Trigger Minikube Deployment (optional)
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.MINIKUBE_HOST }}
          username: ${{ secrets.MINIKUBE_SSH_USER }}
          key: ${{ secrets.MINIKUBE_SSH_KEY }}
          port: 22
          script: |
            cd /Users/suhas/Downloads/sampleCICD
            git pull origin main
            kubectl apply -f deployment.yaml
